apiVersion: apps/v1
kind: Deployment
metadata:
  name: hot-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hotstar
  template:
    metadata:
      labels:
        app: hotstar
    spec:
      containers:
      - name: hotstar-cont
        image: 
        ports:
        - containerPort: 8080
